CREATE TABLE mono_user (ID  SERIAL NOT NULL, EMAIL VARCHAR(255), NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE mono_user_address (ID  SERIAL NOT NULL, CITY VARCHAR(255), NUMBER VARCHAR(255), STREET VARCHAR(255), ZIP VARCHAR(255), user_id BIGINT, PRIMARY KEY (ID))
ALTER TABLE mono_user_address ADD CONSTRAINT FK_mono_user_address_user_id FOREIGN KEY (user_id) REFERENCES mono_user (ID)
